// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

/// Transport method of the signalr connection.
typedef NS_ENUM(NSUInteger, FLTTransport) {
  FLTTransportAuto = 0,
  FLTTransportServerSentEvents = 1,
  FLTTransportLongPolling = 2,
};

/// Wrapper for FLTTransport to allow for nullability.
@interface FLTTransportBox : NSObject
@property(nonatomic, assign) FLTTransport value;
- (instancetype)initWithValue:(FLTTransport)value;
@end

/// SignalR connection status
typedef NS_ENUM(NSUInteger, FLTConnectionStatus) {
  FLTConnectionStatusConnecting = 0,
  FLTConnectionStatusConnected = 1,
  FLTConnectionStatusReconnecting = 2,
  FLTConnectionStatusDisconnected = 3,
  FLTConnectionStatusConnectionSlow = 4,
  FLTConnectionStatusConnectionError = 5,
};

/// Wrapper for FLTConnectionStatus to allow for nullability.
@interface FLTConnectionStatusBox : NSObject
@property(nonatomic, assign) FLTConnectionStatus value;
- (instancetype)initWithValue:(FLTConnectionStatus)value;
@end

@class FLTConnectionOptions;
@class FLTStatusChangeResult;

@interface FLTConnectionOptions : NSObject
+ (instancetype)makeWithBaseUrl:(nullable NSString *)baseUrl
    hubName:(nullable NSString *)hubName
    queryString:(nullable NSString *)queryString
    hubMethods:(nullable NSArray<NSString *> *)hubMethods
    headers:(nullable NSDictionary<NSString *, NSString *> *)headers
    transport:(nullable FLTTransportBox *)transport;
@property(nonatomic, copy, nullable) NSString * baseUrl;
@property(nonatomic, copy, nullable) NSString * hubName;
@property(nonatomic, copy, nullable) NSString * queryString;
@property(nonatomic, copy, nullable) NSArray<NSString *> * hubMethods;
@property(nonatomic, copy, nullable) NSDictionary<NSString *, NSString *> * headers;
@property(nonatomic, strong, nullable) FLTTransportBox * transport;
@end

@interface FLTStatusChangeResult : NSObject
+ (instancetype)makeWithConnectionId:(nullable NSString *)connectionId
    status:(nullable FLTConnectionStatusBox *)status
    errorMessage:(nullable NSString *)errorMessage;
@property(nonatomic, copy, nullable) NSString * connectionId;
@property(nonatomic, strong, nullable) FLTConnectionStatusBox * status;
@property(nonatomic, copy, nullable) NSString * errorMessage;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *FLTGetSignalrApiCodec(void);

@protocol FLTSignalRHostApi
- (void)connectConnectionOptions:(FLTConnectionOptions *)connectionOptions completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)reconnectWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)stopWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)isConnectedWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)invokeMethodMethodName:(NSString *)methodName arguments:(NSArray<NSString *> *)arguments completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpFLTSignalRHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTSignalRHostApi> *_Nullable api);

extern void SetUpFLTSignalRHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTSignalRHostApi> *_Nullable api, NSString *messageChannelSuffix);


@interface FLTSignalRPlatformApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)onStatusChangeStatusChangeResult:(FLTStatusChangeResult *)statusChangeResult completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onNewMessageHubName:(NSString *)hubName message:(NSString *)message completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
